---
require:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/tmp/**/*"
    - "**/vendor/**/*"
    - "test/dummy/**/*"
    - "super_test_engine/**/*"

Layout/EmptyLineAfterMagicComment:
  Enabled: Yes

Sorbet/HasSigil:
  Enabled: Yes
  SuggestedStrictness: "true"
  MinimumStrictness: "false"
  Include:
    - app/**/*
    - lib/super/**/*

Style/FrozenStringLiteralComment:
  Enabled: Yes
  Exclude:
    - "gemfiles/**/*"
    - "test/**/*"

Style/StringLiterals:
  Enabled: Yes
  EnforcedStyle: double_quotes
