version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - &restore_cache
        restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - &install_dependencies
        run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - &save_cache
        save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - &setup_database
        run:
          name: setup database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      - &run_tests
        run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rails test
      - &store_test_results
        store_test_results:
          path: /tmp/test-results
      - &store_artifacts
        store_artifacts:
          path: /tmp/test-results
          destination: test-results

  integration_ruby23_rails50_sprockets:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: switch gemfile
          command: |
            ruby bin/switch.rb rails50 sprockets3
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: regenerate dummy application
          command: |
            bundle exec rails g super_test_engine:dummy
      - *setup_database
      - *run_tests
      - *store_test_results
      - *store_artifacts

  integration_ruby24_rails51_sprockets:
    docker:
      - image: circleci/ruby:2.4.6-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: switch gemfile
          command: |
            ruby bin/switch.rb rails51 sprockets3
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: regenerate dummy application
          command: |
            bundle exec rails g super_test_engine:dummy
      - *setup_database
      - *run_tests
      - *store_test_results
      - *store_artifacts

workflows:
  version: 2
  unit_tests_then_integration:
    jobs:
      - build
      - integration_ruby23_rails50_sprockets:
          requires:
            - build
      - integration_ruby24_rails51_sprockets:
          requires:
            - build
