name: Lint

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: .Gemfile.rubocop
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
      - run: bin/rubocop
