name: Unit tests

on: [push]

jobs:
  test_thoroughly:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails50_sprockets3_ruby23.gemfile
          - gemfiles/rails50_sprockets3.gemfile
          - gemfiles/rails51_sprockets3.gemfile
          - gemfiles/rails52_sprockets4.gemfile
          - gemfiles/rails60_sprockets4.gemfile
          - gemfiles/rails61_sprockets4.gemfile
          - gemfiles/rails70_sprockets4.gemfile
          - gemfiles/rails70_jsbundling4.gemfile
        ruby:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        exclude:
          - ruby: "2.3"
          - ruby: "2.4"
          - ruby: "2.5"
          - ruby: "2.6"
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
        include:
          - gemfile: gemfiles/rails50_sprockets3_ruby23.gemfile
            ruby: "2.3"
          - gemfile: gemfiles/rails50_sprockets3.gemfile
            ruby: "2.4"
          - gemfile: gemfiles/rails51_sprockets3.gemfile
            ruby: "2.5"
          - gemfile: gemfiles/rails52_sprockets4.gemfile
            ruby: "2.5"
          - gemfile: gemfiles/rails60_sprockets4.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails61_sprockets4.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails70_sprockets4.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails70_sprockets4.gemfile
            ruby: "3.0"
          - gemfile: gemfiles/rails70_sprockets4.gemfile
            ruby: "3.1"
          - gemfile: gemfiles/rails70_sprockets4.gemfile
            ruby: "3.2"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      SELENIUM_CHROME: "true"

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    - run: bin/remove_sorbet
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - name: Thoroughly test
      run: ruby bin/thoroughly_test.rb

  test_default:
    runs-on: ubuntu-latest
    env:
      SELENIUM_CHROME: "true"
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - run: bin/rails db:migrate
    - run: bin/rails test

  type_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
        bundler-cache: true
    - run: bin/tapioca gem --verify
    - run: bin/spoom tc
    - run: bin/rails db:migrate
    - run: bin/tapioca dsl --verify
