name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails50_sprockets3.gemfile
          - gemfiles/rails51_sprockets3.gemfile
          - gemfiles/rails52_sprockets4.gemfile
          - gemfiles/rails60_sprockets4.gemfile
          - gemfiles/rails60_webpacker4.gemfile
          - gemfiles/rails60_webpacker5.gemfile
          - gemfiles/rails61_sprockets4.gemfile
          - gemfiles/rails61_webpacker5.gemfile
        ruby:
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
        exclude:
          - ruby: "2.4"
          - ruby: "2.5"
          - ruby: "2.6"
          - ruby: "2.7"
        include:
          - gemfile: gemfiles/rails50_sprockets3.gemfile
            ruby: "2.4"
          - gemfile: gemfiles/rails51_sprockets3.gemfile
            ruby: "2.5"
          - gemfile: gemfiles/rails52_sprockets4.gemfile
            ruby: "2.5"
          - gemfile: gemfiles/rails60_sprockets4.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails60_webpacker4.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails60_webpacker5.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails60_sprockets4.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails61_sprockets4.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails61_webpacker5.gemfile
            ruby: "2.7"

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
        BUNDLE_GEMFILE_LOCK: ${{ github.workspace }}/${{ matrix.gemfile }}.lock
      with:
        path: gemfiles/vendor/bundle
        key: ${{ runner.os }}-Ruby${{ matrix.ruby }}-gems-${{ hashFiles(env.BUNDLE_GEMFILE_LOCK) }}
        restore-keys: |
          ${{ runner.os }}-Ruby${{ matrix.ruby }}-gems-
    - name: Install and set up Bundler
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      run: |
        gem install bundler -v 1.17.3
        bundle config path "$(pwd)/gemfiles/vendor/bundle"
    - name: Test
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      run: |
        ruby bin/thoroughly_test.rb
    - name: Clean Bundler cache
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      run: |
        bundle clean
